name: nlp7-emotion-env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - spacy=3.7.4
  - nltk
  - librosa
  - fastapi
  - uvicorn
  - python-dotenv
  - aiohttp
  - ipykernel
  - matplotlib
  - matplotlib-inline
  - kiwisolver=1.3.1
  - networkx
  - packaging
  - sympy
  - dill
  - filelock
  - fonttools
  - fsspec
  - psutil
  - pyarrow
  - accelerate
  - pip
  - pip:
      - "transformers[torch]==4.36.2"
      - sentencepiece
      - mlflow==2.11.3
      - datasets
      - evaluate
      - mltable>=1.3.0
      - azure-ai-ml
      - azure-identity
      - azureml-core
      - azureml-defaults
      - tqdm==4.66.3
      - sacremoses
      - soundfile
      - python-multipart
      - yt-dlp
      - aiohappyeyeballs
      - annotated-types
      - anyio
      - assemblyai
      - attrs
      - blis==0.7.9
      - catalogue==2.0.10
      - certifi
      - charset-normalizer
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cmudict
      - colorama
      - comm
      - confection==0.0.4
      - contourpy
      - cycler
      - cymem==2.0.11
      - debugpy
      - decorator
      - frozenlist
      - h11
      - httpcore
      - httpx
      - huggingface-hub==0.30.1
      - idna
      - importlib-metadata
      - importlib-resources
      - ipython
      - jedi
      - jinja2
      - joblib
      - langcodes
      - language-data
      - markdown-it-py
      - markupsafe
      - mpmath
      - multidict
      - multiprocess
      - murmurhash==1.0.12
      - nest-asyncio
      - parso
      - pillow
      - platformdirs
      - preshed==3.0.9
      - prompt-toolkit
      - propcache
      - pure-eval
      - pygments
      - pyparsing
      - pyphen
      - python-dateutil
      - pytz
      - pyyaml
      - pyzmq
      - requests==2.32.2
      - textblob
      - textstat==0.7.3
      - thinc
      - vaderSentiment
      - pre-commit
